sonar.projectKey=ApiAnime
sonar.projectName=ApiAnime
sonar.sources=.
sonar.exclusions=node_modules/**,*.test.js
sonar.host.url=http://host.docker.internal:9000
sonar.token=sqp_1392be3ff2b337efd1d9435b1a0e296ba1c18aa2
sonar.coverage.exclusions=**/index.js